version: '3.8'

services:
  app:
    container_name: rpl-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: rpl-db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: