name: CD Workflow
# TODO: Make the binary for the workflow to compile correctly
on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'


      - name: Build binary
        run: go build -o rpl-service ../../main/main.go

      - name: Upload Go artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpl-service
          path: rpl-service


      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          github-token: ${{ secrets.DEPLOY_TOKEN }}
          pages-branch: main
          pages-path: /
